const students = [{
    "id": 1,
    "first_name": "Darleen",
    "last_name": "Dalton",
    "email": "ddalton0@cisco.com",
    "gender": "Agender"
  }, {
    "id": 2,
    "first_name": "Steffane",
    "last_name": "Byrom",
    "email": "sbyrom1@examiner.com",
    "gender": "Polygender"
  }, {
    "id": 3,
    "first_name": "Franz",
    "last_name": "Strudwick",
    "email": "fstrudwick2@seattletimes.com",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Royal",
    "last_name": "O'Crevan",
    "email": "rocrevan3@github.io",
    "gender": "Bigender"
  }, {
    "id": 5,
    "first_name": "Alyse",
    "last_name": "Catterson",
    "email": "acatterson4@nhs.uk",
    "gender": "Genderqueer"
  }, {
    "id": 6,
    "first_name": "Ibrahim",
    "last_name": "Loney",
    "email": "iloney5@cloudflare.com",
    "gender": "Genderfluid"
  }, {
    "id": 7,
    "first_name": "Kori",
    "last_name": "Kobierski",
    "email": "kkobierski6@prlog.org",
    "gender": "Polygender"
  }, {
    "id": 8,
    "first_name": "Rhianon",
    "last_name": "Coling",
    "email": "rcoling7@merriam-webster.com",
    "gender": "Agender"
  }, {
    "id": 9,
    "first_name": "Marjory",
    "last_name": "Hartropp",
    "email": "mhartropp8@businesswire.com",
    "gender": "Female"
  }, {
    "id": 10,
    "first_name": "Tammy",
    "last_name": "Ben",
    "email": "tben9@godaddy.com",
    "gender": "Genderfluid"
  }, {
    "id": 11,
    "first_name": "Katinka",
    "last_name": "Maxwale",
    "email": "kmaxwalea@flickr.com",
    "gender": "Polygender"
  }, {
    "id": 12,
    "first_name": "Harlin",
    "last_name": "Aldwich",
    "email": "haldwichb@sitemeter.com",
    "gender": "Genderqueer"
  }, {
    "id": 13,
    "first_name": "Kym",
    "last_name": "Matuszak",
    "email": "kmatuszakc@tmall.com",
    "gender": "Genderqueer"
  }, {
    "id": 14,
    "first_name": "Sydel",
    "last_name": "Yearns",
    "email": "syearnsd@i2i.jp",
    "gender": "Non-binary"
  }, {
    "id": 15,
    "first_name": "Austin",
    "last_name": "Pennock",
    "email": "apennocke@imdb.com",
    "gender": "Genderfluid"
  }, {
    "id": 16,
    "first_name": "Hollyanne",
    "last_name": "Veltman",
    "email": "hveltmanf@gov.uk",
    "gender": "Genderqueer"
  }, {
    "id": 17,
    "first_name": "Teena",
    "last_name": "Trowell",
    "email": "ttrowellg@msu.edu",
    "gender": "Female"
  }, {
    "id": 18,
    "first_name": "Natassia",
    "last_name": "Bouts",
    "email": "nboutsh@apache.org",
    "gender": "Genderfluid"
  }, {
    "id": 19,
    "first_name": "Tome",
    "last_name": "Longmead",
    "email": "tlongmeadi@cnn.com",
    "gender": "Male"
  }, {
    "id": 20,
    "first_name": "Carmelita",
    "last_name": "Catenot",
    "email": "ccatenotj@theatlantic.com",
    "gender": "Agender"
  }, {
    "id": 21,
    "first_name": "Bevon",
    "last_name": "Rainard",
    "email": "brainardk@devhub.com",
    "gender": "Female"
  }, {
    "id": 22,
    "first_name": "Lucie",
    "last_name": "Linggood",
    "email": "llinggoodl@barnesandnoble.com",
    "gender": "Male"
  }, {
    "id": 23,
    "first_name": "Robby",
    "last_name": "Veasey",
    "email": "rveaseym@samsung.com",
    "gender": "Genderqueer"
  }, {
    "id": 24,
    "first_name": "Poppy",
    "last_name": "Newick",
    "email": "pnewickn@answers.com",
    "gender": "Non-binary"
  }, {
    "id": 25,
    "first_name": "Jolyn",
    "last_name": "Aiskrigg",
    "email": "jaiskriggo@qq.com",
    "gender": "Agender"
  }]



  module.exports = students;